AppCoder/urls.py
from django.urls import path
from . import views

app_name = "AppCoder"

urlpatterns = [
    path("post/list", views.post_list, name="post_list"),
    path("post/create", views.post_create, name="post_create"),
]

Main/urls.py
from django.urls import path
from . import views

app_name = "Main"

urlpatterns = [
    path("", views.index, name="index"),
]

MiProyecto/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Main.urls")),
    path("AppCoder/", include("AppCoder.urls")),
]

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    class Estado(models.TextChoices):
        BORRADOR = "B", "Borrador"
        PUBLICADO = "P", "Publicado"
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(
        max_length=1,
        choices=Estado.choices,
        default=Estado.BORRADOR,
    )

    def __str__(self):
        return self.title

Main/models.py
from django.db import models

# Create your models here.

AppCoder/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'estado']

AppCoder/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm


def post_list(request):
    busqueda = request.GET.get("busqueda", None)
    if busqueda:
        post_list = Post.objects.filter(title__icontains=busqueda)
    else: 
        post_list = Post.objects.all()
    return render(request, 'AppCoder/post_list.html', context={"posts": post_list})

def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            post.save()
            return redirect('AppCoder:post_list')
        else:
            form.add_error(None, "Debes estar logeado para poder publicar")
    else: 
        form = PostForm()
    return render(request, 'AppCoder/post_create.html', context={"form": form}) 

Main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Main/index.html')

AppCoder/templates/AppCoder/post_create.html
{% extends 'Main/base.html' %}

{% block title %}
    Publicar
{% endblock title %}

{% block content_title %}
    Crear nueva publicación
{% endblock content_title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar">
        <a href="{% url 'AppCoder:post_list' %}">Cancelar</a>
    </form>
{% endblock content %}

AppCoder/templates/AppCoder/post_list.html
{% extends 'Main/base.html' %}

{% block title %}
    Publicaciones
{% endblock title %}

{% block content_title %}
    Lista de publicaciones
{% endblock content_title %}

{% block content %}
    <a href="{% url 'AppCoder:post_create' %}" class="btn btn-primary mb-3">Crear nueva publicación</a>
    <form action="{% url 'AppCoder:post_list' %}" method="get">
        <input type="text" name="busqueda" placeholder="Buscar..." type="submit"
        class="form-control mb-3">
    </form>

    <ul class="list-group shadow">
        {% for post in posts %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="fw-bold">{{ post.title }}</span>
                <span class="badge bg-primary rounded-pill">{{ post.created_at }}</span>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

Main/templates/Main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog | {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Mi sitio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'Main:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'AppCoder:post_list' %}">Blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Contacto</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container my-5">
        <h1 class="text-center mb-4">
            {% block content_title %}
            {% endblock content_title %}
        </h1>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>

</html>

Main/templates/Main/index.html
{% extends 'Main/base.html' %}

{% block title %}
    Inicio
{% endblock title %}

{% block content_title %}
    Bienvenido a Mi Blog
{% endblock content_title %}

{% block content %}
    <button>
        <a href="{% url 'AppCoder:post_list' %}">Ingresar</a>
    </button>
{% endblock content %}